FROM rabbitmq:3.7.4

# ----------------------
# add config file and certificates
# ----------------------
COPY ["./broker/rabbitmq.config", "/etc/rabbitmq/rabbitmq.config"]

# ----------------------
# enable plubins
# ----------------------
# RUN rabbitmq-plugins enable --offline rabbitmq_management
RUN rabbitmq-plugins enable --offline rabbitmq_mqtt
RUN rabbitmq-plugins enable --offline rabbitmq_web_mqtt
RUN rabbitmq-plugins enable --offline rabbitmq_auth_backend_http
